### ISSUE TITLE
bug: Show posters/thumbnails not visible in Jellyfin

### ISSUE THREAD

**Issue by sannidhyaroy** [rabilrbl/jiotv_go#369]
### Feature description

In Jellyfin, there's no image for a show in the Dashboard of the Web UI. It would be more intuitive to show the show thumbnail, and if it's not possible, at least to show the channel logo as a thumbnail.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Can U show the requests from network tab?

**Comment by rabilrbl** [comment]
@sannidhyaroy What does the logs in jellyfin say?

**Comment by sannidhyaroy** [comment]
These are a portion of the logs related to this thread of Jellyfin:
```
Aug 14 18:32:40 raspberrypi jellyfin[578]: [18:32:40] [ERR] Failed to determine primary image aspect ratio for /jtvposter/2024-08-14/2408141079018.jpg
Aug 14 18:32:40 raspberrypi jellyfin[578]: System.IO.FileNotFoundException: File not found
Aug 14 18:32:40 raspberrypi jellyfin[578]: File name: '/jtvposter/2024-08-14/2408141079018.jpg'
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
Aug 14 18:32:40 raspberrypi jellyfin[578]: [18:32:40] [ERR] Failed to determine primary image aspect ratio for /jtvposter/2024-08-14/2408141430018.jpg
Aug 14 18:32:40 raspberrypi jellyfin[578]: System.IO.FileNotFoundException: File not found
Aug 14 18:32:40 raspberrypi jellyfin[578]: File name: '/jtvposter/2024-08-14/2408141430018.jpg'
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
Aug 14 18:32:40 raspberrypi jellyfin[578]: [18:32:40] [ERR] Failed to determine primary image aspect ratio for /jtvposter/2024-08-14/2408141763006.jpg
Aug 14 18:32:40 raspberrypi jellyfin[578]: System.IO.FileNotFoundException: File not found
Aug 14 18:32:40 raspberrypi jellyfin[578]: File name: '/jtvposter/2024-08-14/2408141763006.jpg'
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
Aug 14 18:32:40 raspberrypi jellyfin[578]: [18:32:40] [ERR] Failed to determine primary image aspect ratio for /jtvposter/2024-08-14/2408142853056.jpg
Aug 14 18:32:40 raspberrypi jellyfin[578]: System.IO.FileNotFoundException: File not found
Aug 14 18:32:40 raspberrypi jellyfin[578]: File name: '/jtvposter/2024-08-14/2408142853056.jpg'
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
Aug 14 18:32:40 raspberrypi jellyfin[578]: [18:32:40] [ERR] Failed to determine primary image aspect ratio for /jtvposter/2024-08-14/240814415006.jpg
Aug 14 18:32:40 raspberrypi jellyfin[578]: System.IO.FileNotFoundException: File not found
Aug 14 18:32:40 raspberrypi jellyfin[578]: File name: '/jtvposter/2024-08-14/240814415006.jpg'
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
Aug 14 18:32:40 raspberrypi jellyfin[578]: [18:32:40] [ERR] Failed to determine primary image aspect ratio for /jtvposter/2024-08-14/240814155018.jpg
Aug 14 18:32:40 raspberrypi jellyfin[578]: System.IO.FileNotFoundException: File not found
Aug 14 18:32:40 raspberrypi jellyfin[578]: File name: '/jtvposter/2024-08-14/240814155018.jpg'
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
Aug 14 18:32:40 raspberrypi jellyfin[578]: [18:32:40] [ERR] Failed to determine primary image aspect ratio for /jtvposter/2024-08-14/240814175019.jpg
Aug 14 18:32:40 raspberrypi jellyfin[578]: System.IO.FileNotFoundException: File not found
Aug 14 18:32:40 raspberrypi jellyfin[578]: File name: '/jtvposter/2024-08-14/240814175019.jpg'
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
Aug 14 18:32:40 raspberrypi jellyfin[578]: [18:32:40] [ERR] Failed to determine primary image aspect ratio for /jtvposter/2024-08-14/240814288028.jpg
Aug 14 18:32:40 raspberrypi jellyfin[578]: System.IO.FileNotFoundException: File not found
Aug 14 18:32:40 raspberrypi jellyfin[578]: File name: '/jtvposter/2024-08-14/240814288028.jpg'
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
Aug 14 18:32:40 raspberrypi jellyfin[578]: [18:32:40] [ERR] Failed to determine primary image aspect ratio for /jtvposter/2024-08-14/240814466031.jpg
Aug 14 18:32:40 raspberrypi jellyfin[578]: System.IO.FileNotFoundException: File not found
Aug 14 18:32:40 raspberrypi jellyfin[578]: File name: '/jtvposter/2024-08-14/240814466031.jpg'
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Aug 14 18:32:40 raspberrypi jellyfin[578]:    at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
```

These logs are continuously generated while navigating within the Jellyfin Web UI. No matter which button (even those that aren't part of Live TV) you click in the Web UI, such logs are continuously generated.

**Comment by mohit-kothari** [comment]
@rabilrbl Is there any reason why jiotv_go has its own url for posters instead of using jio's urls directly?

I changed code to update icon url from `/jtvposter/2024-09-02/240902146031.jpg` to `https://jiotv.catchup.cdn.jio.com/dare_images/shows/2024-09-02/240902146031.jpg` and I can see thumbnails now.

![image](https://github.com/user-attachments/assets/572fabc3-48b8-413f-99e0-31b42f189875)

**Comment by rabilrbl** [comment]
> @rabilrbl Is there any reason why jiotv_go has its own url for posters instead of using jio's urls directly?
> 
> I changed code to update icon url from `/jtvposter/2024-09-02/240902146031.jpg` to `https://jiotv.catchup.cdn.jio.com/dare_images/shows/2024-09-02/240902146031.jpg` and I can see thumbnails now.
> 
> ![image](https://private-user-images.githubusercontent.com/36753600/364087679-572fabc3-48b8-413f-99e0-31b42f189875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjQxMTQsIm5iZiI6MTcyNTQyMzgxNCwicGF0aCI6Ii8zNjc1MzYwMC8zNjQwODc2NzktNTcyZmFiYzMtNDhiOC00MTNmLTk5ZTAtMzFiNDJmMTg5ODc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA0MjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkODIzNzQzMGEwNDgzNzQzNTUwM2IzMzk0MjYwZTgwZTZjNjkxOGMxMjNjMThkZjAxYzE4YThiOGRlYzkwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZxWvs_SMEJOqXwvXGLG0k8eyo8HEjeqrmDOLVteNCu4)

It's there for proxying requests through server. I can keep an option to disable it. It will work even if we provide entire server url instead

**Comment by mohit-kothari** [comment]
Yes, either that. Or we can add an variable to set thumbnail prefix address in env. Which means for someone who has fixed static address for their Jiotv_go server (which I am assuming most people running jellyfin will already have), we can pass `http://<ipaddress>:5001/jtvposter` in this variable and still have proxy. And if someone prefers to use jio's cdn directly, then can pass `https://jiotv.catchup.cdn.jio.com/dare_images/shows`. If this variable is set we can just appent it to thumbnail path.

**Comment by rabilrbl** [comment]
> Yes, either that. Or we can add an variable to set thumbnail prefix address in env. Which means for someone who has fixed static address for their Jiotv_go server (which I am assuming most people running jellyfin will already have), we can pass `http://<ipaddress>:5001/jtvposter` in this variable and still have proxy. And if someone prefers to use jio's cdn directly, then can pass `https://jiotv.catchup.cdn.jio.com/dare_images/shows`. If this variable is set we can just appent it to thumbnail path.

JioTV Go can find such addresses automatically. No need for manual config. When cdn proxy is disabled option will use jio CDN

**Comment by mohit-kothari** [comment]
Got it, but what i mean is let's see I am using proxy and want to use this server with jellyfin too. Then in that case of epg still returns urls starting with /jtvposter, then jellyfin won't be able to show images. Also EPG generation being seperate process, we cannot just pick current host name from incoming request right?

So how will jiotv_go know the host automatically?

**Comment by rabilrbl** [comment]
You're right. I forgot about epg command
For now as a temporary fix and I don't have time. Will server posters directly from Jio CDN for epg files

**Comment by rabilrbl** [comment]
@mohit-kothari @sannidhyaroy I believe channel logos are visible? Because I didn't have any problems in jellyfin myself

**Comment by mohit-kothari** [comment]
@rabilrbl Channel logos have never been problem. We are talking about program poster.

![image](https://github.com/user-attachments/assets/0442b735-f0f4-4b99-9d86-b5cc759099e1)

**Comment by sannidhyaroy** [comment]
> @mohit-kothari @sannidhyaroy I believe channel logos are visible? Because I didn't have any problems in jellyfin myself

Channel logos are shown correctly. I never had a problem with that.

**Comment by prashantcruise** [comment]
> > @mohit-kothari @sannidhyaroy I believe channel logos are visible? Because I didn't have any problems in jellyfin myself
> 
> Channel logos are shown correctly. I never had a problem with that.

Hey how you have setup jio tv in jellyfin? 
Live tv > add m3u playlist url still!! What I am missing?

**Comment by sannidhyaroy** [comment]
> Hey how you have setup jio tv in jellyfin? 
> Live tv > add m3u playlist url still!! What am I missing? 

Live TV > Add M3U Tuner and save it.
Next, add TV Guide Data Providers > XMLTV and save it.

**Comment by rabilrbl** [comment]
@mohit-kothari @sannidhyaroy  I don't think changing poster urls directly to Jio CDN is working for me in jellyfin
Can you guys latest pre-release / docker image with tag `:develop`?
