### ISSUE TITLE
bug:Request failed with status code: 450

### ISSUE THREAD

**Issue by Hackerche** [rabilrbl/jiotv_go#380]
### Bug description

Whenever I'm trying to run jio tv go I get this error

### Steps to reproduce

When i am simply trying to run it on my pc

### Relevant log output

```shell
panic: Request failed with status code: 450                                                             goroutine 29 [running]:                                                                                 runtime/debug.Stack()                                                                                           runtime/debug/stack.go:24 +0x5e                                                                 github.com/gofiber/fiber/v2/middleware/recover.defaultStackTraceHandler(0x8ecc25?, {0xe517a0, 0xc000031930})                                                                                                            github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:12 +0x25                      github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1.1()                                                   github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:31 +0x74                      panic({0xe517a0?, 0xc000031930?})                                                                               runtime/panic.go:770 +0x132                                                                     log.(*Logger).Panicf(0xc0001bb1a0, {0xf1c5b7?, 0xc000049dc0?}, {0xc000035290?, 0xefd545?, 0x3?})                log/log.go:310 +0x6e                                                                            github.com/rabilrbl/jiotv_go/v3/pkg/television.Channels()                                                       github.com/rabilrbl/jiotv_go/v3/pkg/television/television.go:202 +0x59a                         github.com/rabilrbl/jiotv_go/v3/internal/handlers.IndexHandler(0xc00001a308)                                    github.com/rabilrbl/jiotv_go/v3/internal/handlers/handlers.go:81 +0x2a                          github.com/gofiber/fiber/v2.(*App).next(0xc0002a2008, 0xc00001a308)                                             github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be                                        github.com/gofiber/fiber/v2.(*Ctx).Next(0x0?)                                                                   github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1034 +0x4d                                           github.com/gofiber/fiber/v2/middleware/etag.New.func1(0xc00001a308)                                             github.com/gofiber/fiber/v2@v2.52.5/middleware/etag/etag.go:33 +0xb7                            github.com/gofiber/fiber/v2.(*Ctx).Next(0xc00001a308?)                                                          github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1031 +0x3d                                           github.com/gofiber/fiber/v2/middleware/helmet.New.func1(0xc00001a308)                                           github.com/gofiber/fiber/v2@v2.52.5/middleware/helmet/helmet.go:92 +0x53f                       github.com/gofiber/fiber/v2.(*App).next(0xc0002a2008, 0xc00001a308)                                             github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be                                        github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0002bde60?)                                                          github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1034 +0x4d                                           github.com/gofiber/fiber/v2/middleware/logger.New.func3(0xc00001a308)                                           github.com/gofiber/fiber/v2@v2.52.5/middleware/logger/logger.go:119 +0x316                      github.com/gofiber/fiber/v2.(*Ctx).Next(0xc00000b9e0?)                                                          github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1031 +0x3d                                           github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.CORS.func2(0xc00001a308)                                        github.com/rabilrbl/jiotv_go/v3/internal/middleware/cors.go:30 +0x147                           github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000056008?)                                                          github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1031 +0x3d                                           github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1(0xe77120?)                                            github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:43 +0xbb                      github.com/gofiber/fiber/v2.(*App).next(0xc0002a2008, 0xc00001a308)                                             github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be                                        github.com/gofiber/fiber/v2.(*App).handler(0xc0002a2008, 0x98710f?)                                             github.com/gofiber/fiber/v2@v2.52.5/router.go:172 +0x78                                         github.com/valyala/fasthttp.(*Server).serveConn(0xc0000de6c8, {0x113e050, 0xc00009a8a8})                        github.com/valyala/fasthttp@v1.55.0/server.go:2379 +0xe70                                       github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000127ae0, 0xc0001b6f80)                                github.com/valyala/fasthttp@v1.55.0/workerpool.go:224 +0xa4                                     github.com/valyala/fasthttp.(*workerPool).getCh.func1()                                                         github.com/valyala/fasthttp@v1.55.0/workerpool.go:196 +0x32                                     created by github.com/valyala/fasthttp.(*workerPool).getCh in goroutine 1                                       github.com/valyala/fasthttp@v1.55.0/workerpool.go:195 +0x190                                                                                                                                            panic: Request failed with status code: 450                                                             goroutine 10 [running]:                                                                                 runtime/debug.Stack()                                                                                           runtime/debug/stack.go:24 +0x5e                                                                 github.com/gofiber/fiber/v2/middleware/recover.defaultStackTraceHandler(0x8ecc25?, {0xe517a0, 0xc0002bf840})                                                                                                            github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:12 +0x25                      github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1.1()                                                   github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:31 +0x74                      panic({0xe517a0?, 0xc0002bf840?})                                                                               runtime/panic.go:770 +0x132                                                                     log.(*Logger).Panicf(0xc0001bb1a0, {0xf1c5b7?, 0xc000080700?}, {0xc000305290?, 0xefd545?, 0x3?})                log/log.go:310 +0x6e                                                                            github.com/rabilrbl/jiotv_go/v3/pkg/television.Channels()                                                       github.com/rabilrbl/jiotv_go/v3/pkg/television/television.go:202 +0x59a                         github.com/rabilrbl/jiotv_go/v3/internal/handlers.IndexHandler(0xc000300008)                                    github.com/rabilrbl/jiotv_go/v3/internal/handlers/handlers.go:81 +0x2a                          github.com/gofiber/fiber/v2.(*App).next(0xc0002a2008, 0xc000300008)                                             github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be                                        github.com/gofiber/fiber/v2.(*Ctx).Next(0x0?)                                                                   github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1034 +0x4d                                           github.com/gofiber/fiber/v2/middleware/etag.New.func1(0xc000300008)                                             github.com/gofiber/fiber/v2@v2.52.5/middleware/etag/etag.go:33 +0xb7                            github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000300008?)                                                          github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1031 +0x3d                                           github.com/gofiber/fiber/v2/middleware/helmet.New.func1(0xc000300008)                                           github.com/gofiber/fiber/v2@v2.52.5/middleware/helmet/helmet.go:92 +0x53f                       github.com/gofiber/fiber/v2.(*App).next(0xc0002a2008, 0xc000300008)                                             github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be                                        github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0002bde60?)                                                          github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1034 +0x4d                                           github.com/gofiber/fiber/v2/middleware/logger.New.func3(0xc000300008)                                           github.com/gofiber/fiber/v2@v2.52.5/middleware/logger/logger.go:119 +0x316                      github.com/gofiber/fiber/v2.(*Ctx).Next(0xc00028d080?)                                                          github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1031 +0x3d                                           github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.CORS.func2(0xc000300008)                                        github.com/rabilrbl/jiotv_go/v3/internal/middleware/cors.go:30 +0x147                           github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0002e7b38?)                                                          github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1031 +0x3d                                           github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1(0xe77120?)                                            github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:43 +0xbb                      github.com/gofiber/fiber/v2.(*App).next(0xc0002a2008, 0xc000300008)                                             github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be                                        github.com/gofiber/fiber/v2.(*App).handler(0xc0002a2008, 0x98710f?)                                             github.com/gofiber/fiber/v2@v2.52.5/router.go:172 +0x78                                         github.com/valyala/fasthttp.(*Server).serveConn(0xc0000de6c8, {0x113e050, 0xc0000524a8})                        github.com/valyala/fasthttp@v1.55.0/server.go:2379 +0xe70                                       github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000127ae0, 0xc0001b6fa0)                                github.com/valyala/fasthttp@v1.55.0/workerpool.go:224 +0xa4                                     github.com/valyala/fasthttp.(*workerPool).getCh.func1()                                                         github.com/valyala/fasthttp@v1.55.0/workerpool.go:196 +0x32                                     created by github.com/valyala/fasthttp.(*workerPool).getCh in goroutine 1                                       github.com/valyala/fasthttp@v1.55.0/workerpool.go:195 +0x190                                                                                                                                            ^C
```

### Screenshots or videos

![image](https://github.com/user-attachments/assets/6d401a35-556f-4ad1-952a-2b9dd02840d1)

### Additional context

Please Get this Issue solved ASAP

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Please read https://jiotv_go.rabil.me/cloud_hosting.html

**Comment by saswattech9** [comment]
i am hosting in my raspberry pi in india with jio network still the same error

**Comment by rabilrbl** [comment]
@saswattech9 You have something to figure out with your network configuration and see if it's behind a proxy or VPN tunnel.
I am using it on Jio network and it works fine

**Comment by saswattech9** [comment]
this is working with jio sim network not on fiber

**Comment by rabilrbl** [comment]
> this is working with jio sim network not on fiber

I meant the jio fiber network itself

**Comment by saswattech9** [comment]
yes, not working on jio fiber network.
