### ISSUE TITLE
bug: Showing Error lookup jiotvapi.cdn.jio.com: i/o timeout on Browser

### ISSUE THREAD

**Issue by bsahane** [rabilrbl/jiotv_go#394]
### Bug description

I have Docker Installed on Linux Machine,
When I am running Docker Container then it shwoing error as,
`lookup jiotvapi.cdn.jio.com: i/o timeout` when verified on Browser,

### Steps to reproduce

Step 1. Run Command,
```
docker run -p 5001:5001 -v ./.jiotv_go/secrets:/app/secrets ghcr.io/rabilrbl/jiotv_go
```
Step 2. Open Link in Browser
```
http://127.0.0.1:5001
```
Step 3. Its showing
```
lookup jiotvapi.cdn.jio.com: i/o timeout
```

### Relevant log output

```shell
When I checked the Container Logs then go this

serve-1  | INFO: You are exposing your server to outside your local network (public)!
serve-1  | INFO: Overwriting host to 0.0.0.0 for public access
serve-1  | INFO: No config file found, using environment variables
serve-1  | 
serve-1  |  ┌───────────────────────────────────────────────────┐ 
serve-1  |  │                     JioTV Go                      │ 
serve-1  |  │                   Fiber v2.52.5                   │ 
serve-1  |  │               http://127.0.0.1:5001               │ 
serve-1  |  │       (bound on host 0.0.0.0 and port 5001)       │ 
serve-1  |  │                                                   │ 
serve-1  |  │ Handlers ............ 48  Processes ........... 1 │ 
serve-1  |  │ Prefork ....... Disabled  PID ................. 1 │ 
serve-1  |  └───────────────────────────────────────────────────┘ 
serve-1  | 
serve-1  | panic: lookup jiotvapi.cdn.jio.com: i/o timeout
serve-1  | goroutine 33 [running]:
serve-1  | runtime/debug.Stack()
serve-1  | 	runtime/debug/stack.go:26 +0x5e
serve-1  | github.com/gofiber/fiber/v2/middleware/recover.defaultStackTraceHandler(0x4373c5?, {0x9bd140, 0xc00010e160})
serve-1  | 	github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:12 +0x25
serve-1  | github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1.1()
serve-1  | 	github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:31 +0x74
serve-1  | panic({0x9bd140?, 0xc00010e160?})
serve-1  | 	runtime/panic.go:785 +0x132
serve-1  | log.(*Logger).Panic(0xc0002752f0, {0xc00012b5d8?, 0xc000084fc0?, 0x0?})
serve-1  | 	log/log.go:303 +0x65
serve-1  | github.com/rabilrbl/jiotv_go/v3/pkg/television.Channels()
serve-1  | 	github.com/rabilrbl/jiotv_go/v3/pkg/television/television.go:190 +0x505
serve-1  | github.com/rabilrbl/jiotv_go/v3/internal/handlers.IndexHandler(0xc0002fc008)
serve-1  | 	github.com/rabilrbl/jiotv_go/v3/internal/handlers/handlers.go:84 +0x2a
serve-1  | github.com/gofiber/fiber/v2.(*App).next(0xc0000c9408, 0xc0002fc008)
serve-1  | 	github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be
serve-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0002bc1e0?)
serve-1  | 	github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1034 +0x4d
serve-1  | github.com/gofiber/fiber/v2/middleware/logger.New.func3(0xc0002fc008)
serve-1  | 	github.com/gofiber/fiber/v2@v2.52.5/middleware/logger/logger.go:119 +0x2ed
serve-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0002c24e8?)
serve-1  | 	github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1031 +0x3d
serve-1  | github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.CORS.func2(0xc0002fc008)
serve-1  | 	github.com/rabilrbl/jiotv_go/v3/internal/middleware/cors.go:30 +0x147
serve-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0002f3b40?)
serve-1  | 	github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1031 +0x3d
serve-1  | github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1(0x9e4cc0?)
serve-1  | 	github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:43 +0xbb
serve-1  | github.com/gofiber/fiber/v2.(*App).next(0xc0000c9408, 0xc0002fc008)
serve-1  | 	github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be
serve-1  | github.com/gofiber/fiber/v2.(*App).handler(0xc0000c9408, 0x4e030f?)
serve-1  | 	github.com/gofiber/fiber/v2@v2.52.5/router.go:172 +0x69
serve-1  | github.com/valyala/fasthttp.(*Server).serveConn(0xc0000d4b48, {0xcb3f90, 0xc00011c010})
serve-1  | 	github.com/valyala/fasthttp@v1.55.0/server.go:2379 +0xe70
serve-1  | github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000272be0, 0xc00013a000)
serve-1  | 	github.com/valyala/fasthttp@v1.55.0/workerpool.go:224 +0x91
serve-1  | github.com/valyala/fasthttp.(*workerPool).getCh.func1()
serve-1  | 	github.com/valyala/fasthttp@v1.55.0/workerpool.go:196 +0x32
serve-1  | created by github.com/valyala/fasthttp.(*workerPool).getCh in goroutine 1
serve-1  | 	github.com/valyala/fasthttp@v1.55.0/workerpool.go:195 +0x190
serve-1  | 
```
```


### Screenshots or videos

![Screenshot 2024-08-30 100030](https://github.com/user-attachments/assets/a20379af-39d0-40e5-9395-74139bc11344)


### Solution

_No response_

### Additional context

I have tried to Remove Existing Container including Image and tried to Run again but Still showing the Same error

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
This is your system related. Change your DNS and make sure docker networks are configured properly.

**Comment by bsahane** [comment]
Thank You @rabilrbl ,
I have changed Network from `bridge` to `host` Network and this helped to Start the Container Properly

Thank You for Your Help and Support!!

**Comment by rabilrbl** [comment]
> Thank You @rabilrbl ,
> I have changed Network from `bridge` to `host` Network and this helped to Start the Container Properly
> 
> Thank You for Your Help and Support!!

That shouldn't be an ideal setup. The host network should not be given access unless absolutely necessary.
You should debug it.
