### ISSUE TITLE
bug: Request failed with status code: 503

### ISSUE THREAD

**Issue by ankitnaik1** [rabilrbl/jiotv_go#432]
### Bug description

panic: Request failed with status code: 503
on latest docker image

### Steps to reproduce

step 1: docker run -p 5001:5001 -v $(pwd)/JioTV_Go:/app/.jiotv_go ghcr.io/rabilrbl/jiotv_go  
step 2: Open http://localhost:5001/

### Relevant log output

```shell
INFO: Skipping update check
INFO: You are exposing your server to outside your local network (public)!
INFO: Overwriting host to 0.0.0.0 for public access
INFO: No config file found, using environment variables

 ┌───────────────────────────────────────────────────┐ 
 │                     JioTV Go                      │ 
 │                   Fiber v2.52.5                   │ 
 │               http://127.0.0.1:5001               │ 
 │       (bound on host 0.0.0.0 and port 5001)       │ 
 │                                                   │ 
 │ Handlers ............ 48  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ................. 1 │ 
 └───────────────────────────────────────────────────┘ 

panic: Request failed with status code: 503
goroutine 22 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x5e
github.com/gofiber/fiber/v2/middleware/recover.defaultStackTraceHandler(0x4373c5?, {0x9be1c0, 0xc00009cdf0})
        github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:12 +0x25
github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1.1()
        github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:31 +0x74
panic({0x9be1c0?, 0xc00009cdf0?})
        runtime/panic.go:785 +0x132
log.(*Logger).Panicf(0xc0001e9410, {0xa8cf75?, 0xc000112fc0?}, {0xc0000f35d8?, 0xa70191?, 0x3?})
        log/log.go:310 +0x6e
github.com/rabilrbl/jiotv_go/v3/pkg/television.Channels()
        github.com/rabilrbl/jiotv_go/v3/pkg/television/television.go:197 +0x58b
github.com/rabilrbl/jiotv_go/v3/internal/handlers.IndexHandler(0xc000266008)
        github.com/rabilrbl/jiotv_go/v3/internal/handlers/handlers.go:88 +0x2a
github.com/gofiber/fiber/v2.(*App).next(0xc000149408, 0xc000266008)
        github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000232330?)
        github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1034 +0x4d
github.com/gofiber/fiber/v2/middleware/logger.New.func3(0xc000266008)
        github.com/gofiber/fiber/v2@v2.52.5/middleware/logger/logger.go:119 +0x2ed
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000236558?)
        github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1031 +0x3d
github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.CORS.func2(0xc000266008)
        github.com/rabilrbl/jiotv_go/v3/internal/middleware/cors.go:30 +0x147
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000080008?)
        github.com/gofiber/fiber/v2@v2.52.5/ctx.go:1031 +0x3d
github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1(0x9e5da0?)
        github.com/gofiber/fiber/v2@v2.52.5/middleware/recover/recover.go:43 +0xbb
github.com/gofiber/fiber/v2.(*App).next(0xc000149408, 0xc000266008)
        github.com/gofiber/fiber/v2@v2.52.5/router.go:145 +0x1be
github.com/gofiber/fiber/v2.(*App).handler(0xc000149408, 0x4e058f?)
        github.com/gofiber/fiber/v2@v2.52.5/router.go:172 +0x69
github.com/valyala/fasthttp.(*Server).serveConn(0xc000150b48, {0xcb5570, 0xc00010abd0})
        github.com/valyala/fasthttp@v1.55.0/server.go:2379 +0xe70
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0001e6b40, 0xc0001f57a0)
        github.com/valyala/fasthttp@v1.55.0/workerpool.go:224 +0x91
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        github.com/valyala/fasthttp@v1.55.0/workerpool.go:196 +0x32
created by github.com/valyala/fasthttp.(*workerPool).getCh in goroutine 1
        github.com/valyala/fasthttp@v1.55.0/workerpool.go:195 +0x190
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by itsyourap** [comment]
The problem is JioTV itself. Jio services were mostly down due to [fire at one of their data centers](https://x.com/ashoknoorpur/status/1835936729557069921). Currently at the time of writing this comment, Jio is still partially down.

The issue will be automatically fixed once JioTV services are up.

**Comment by ankitnaik1** [comment]
Closed as it was due to issue from JioTV end
